version: "3.8"
services: 
  node_backend:
    container_name: rest-api-docker
    image: rest-api-docker:0.0.6
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE=mydb
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:latest"
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    volumes:
      - nps_data:/var/lib/postgresql/data
  
volumes:
  nps_data: {}